---
name: Security Scans
run-name: Security Scans run by ${{ github.actor }}
on: [pull_request, push, workflow_dispatch]
jobs:

  # https://github.com/gitleaks/gitleaks-action?tab=readme-ov-file#environment-variables
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_VERSION: latest
